apiVersion: v1
kind: Service
metadata:
  name: node-mongo-devops-service
spec:
  type: NodePort
  selector:
    app: node-mongo-devops-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30001
